#!/usr/bin/env python3
"""MCP Prompts server for skill: sprint-grooming (v0.1.0).

Generated by skills-forge  <https://github.com/ficiverson/skills-forge>

Run with uvx (no install):
    uvx --from "mcp[cli]" mcp run sprint-grooming-mcp-server.py

Run with Python:
    pip install mcp
    python sprint-grooming-mcp-server.py

Add to Claude Desktop (~/Library/Application Support/Claude/claude_desktop_config.json):
    {
      "mcpServers": {
        "sprint-grooming": {
          "command": "uvx",
          "args": ["--from", "mcp[cli]", "mcp", "run", "/absolute/path/to/sprint-grooming-mcp-server.py"]
        }
      }
    }
"""

from __future__ import annotations

from mcp.server.fastmcp import FastMCP

# ── skill payload ─────────────────────────────────────────────────────────────

SKILL_NAME: str = 'sprint-grooming'
SKILL_DESCRIPTION: str = 'Convert rough ideas into production-ready user stories.\nTriggers on: sprint, grooming, user story, backlog, acceptance criteria.'
SKILL_BODY: str = 'You are a specialist assistant for sprint-grooming.\nConvert rough ideas into production-ready user stories.\nTriggers on: sprint, grooming, user story, backlog, acceptance criteria.\n\n---\n\n## Workflow\n\n1. Read the input.\n2. Write the user story.'

# ── MCP server ────────────────────────────────────────────────────────────────

mcp = FastMCP(SKILL_NAME)


@mcp.prompt(name=SKILL_NAME, description=SKILL_DESCRIPTION)
def sprint_grooming() -> str:
    """Exported skill prompt."""
    return SKILL_BODY


if __name__ == "__main__":
    mcp.run()
