"""Bedrock-XML exporter.

Produces an AWS Bedrock agent prompt XML template compatible with the
Bedrock Prompt Management API and the Bedrock Agent "advanced prompts" system.

The XML follows the Anthropic Claude prompt-template schema used in
Bedrock orchestration:  ``$system$``, ``$human_turn$``, ``$model_response$``
are substitution variables that Bedrock replaces at inference time.

Output filename: ``<name>.bedrock.xml``

Usage
-----
Bedrock Prompt Management (console):
  1. AWS Console → Amazon Bedrock → Prompt management → Create prompt
  2. Choose "Text" as the template type, select a Claude model.
  3. Paste the ``<system>`` block content into the System prompt field.
  4. Use the ``<human>`` block as your "User message" template.

Bedrock Agents (advanced prompts):
  1. AWS Console → Amazon Bedrock → Agents → your-agent → Edit
  2. Under "Advanced prompts", enable the "Orchestration" template override.
  3. Paste the full XML (or just the system block) into the template editor.

Reference
---------
https://docs.aws.amazon.com/bedrock/latest/userguide/prompt-management-create.html
https://docs.aws.amazon.com/bedrock/latest/userguide/advanced-prompts-templates.html
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path

from skill_forge.domain.model import ExportFormat, Skill
from skill_forge.domain.ports import SkillExporter


def _xml_text(tag: str, text: str) -> str:
    """Return ``<tag>text</tag>`` with minimal escaping via stdlib ET."""
    elem = ET.Element(tag)
    elem.text = text
    return ET.tostring(elem, encoding="unicode", xml_declaration=False)


class BedrockXmlExporter(SkillExporter):
    """Export a skill as an AWS Bedrock agent prompt XML template."""

    format = ExportFormat.BEDROCK_XML

    def export(self, skill: Skill, body: str, output_dir: Path) -> Path:
        output_dir.mkdir(parents=True, exist_ok=True)

        system_text = (
            f"You are a specialist assistant for {skill.identity.name}.\n"
            f"{skill.description.text.strip()}\n\n"
            f"{body}"
        )

        lines = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            "<!--",
            f"  Bedrock prompt template for skill: {skill.identity.name} v{skill.version}",
            "  Generated by skills-forge.",
            "",
            "  Variables:",
            "    $system$           — replaced with system prompt at runtime (if using",
            "                         Bedrock Prompt Management template variables)",
            "    $human_turn$       — replaced with the user's input",
            "    $model_response$   — Bedrock inserts the model's response here",
            "-->",
            "<PromptTemplate>",
            "  <system>",
        ]

        # Indent the system text inside the element
        for line in system_text.splitlines():
            lines.append(f"    {line}" if line else "")
        lines += [
            "  </system>",
            "",
            "  <!-- Replace $human_turn$ with the user's message at runtime. -->",
            "  <human>$human_turn$</human>",
            "",
            "  <!-- Bedrock fills in $model_response$ automatically. -->",
            "  <assistant>$model_response$</assistant>",
            "",
            "  <metadata>",
            f"    <skill>{skill.identity.name}</skill>",
            f"    <version>{skill.version}</version>",
            f"    <category>{skill.identity.category}</category>",
            "    <source>skills-forge</source>",
            "  </metadata>",
            "</PromptTemplate>",
        ]

        content = "\n".join(lines)

        out = output_dir / f"{skill.identity.slug}.bedrock.xml"
        out.write_text(content, encoding="utf-8")
        return out
