"""MCP-server exporter.

Generates a self-contained Python MCP (Model Context Protocol) server that
exposes the skill as an MCP ``Prompt`` primitive.  Any MCP-capable host
(Claude Desktop, Cursor, VS Code, OpenAI desktop app, etc.) can connect to
it and inject the skill at inference time — no installation step needed.

The generated server uses the official ``mcp`` Python SDK.  It is a single
file that can be run with ``uvx`` (no install required) or plain ``python``.

Output
------
A single file: ``<output_dir>/<name>-mcp-server.py``

Usage after export
------------------
**Run with uvx (recommended — zero install):**

    uvx --from mcp mcp-run <name>-mcp-server.py

**Run with Python:**

    pip install mcp
    python <name>-mcp-server.py

**Add to Claude Desktop** (``~/Library/Application Support/Claude/claude_desktop_config.json``):

    {
      "mcpServers": {
        "<name>": {
          "command": "python",
          "args": ["/absolute/path/to/<name>-mcp-server.py"]
        }
      }
    }

**Add to Cursor** (``.cursor/mcp.json``):

    {
      "mcpServers": {
        "<name>": {
          "command": "python",
          "args": ["/absolute/path/to/<name>-mcp-server.py"]
        }
      }
    }

Reference
---------
https://modelcontextprotocol.io/quickstart/server
https://github.com/modelcontextprotocol/python-sdk
"""

from __future__ import annotations

from pathlib import Path

from skill_forge.domain.model import ExportFormat, Skill
from skill_forge.domain.ports import SkillExporter

# ── template ─────────────────────────────────────────────────────────────────

_SERVER_TEMPLATE = '''\
#!/usr/bin/env python3
"""MCP Prompts server for skill: {name} (v{version}).

Generated by skills-forge  <https://github.com/ficiverson/skills-forge>

Run with uvx (no install):
    uvx --from mcp mcp-run {slug}-mcp-server.py

Run with Python:
    pip install mcp
    python {slug}-mcp-server.py

Add to Claude Desktop (~/Library/Application Support/Claude/claude_desktop_config.json):
    {{
      "mcpServers": {{
        "{name}": {{
          "command": "python",
          "args": ["/absolute/path/to/{slug}-mcp-server.py"]
        }}
      }}
    }}
"""

from __future__ import annotations

import asyncio

from mcp import types
from mcp.server import Server
from mcp.server.stdio import stdio_server

# ── skill payload ─────────────────────────────────────────────────────────────

SKILL_NAME: str = {name_repr}
SKILL_DESCRIPTION: str = {description_repr}
SKILL_BODY: str = {body_repr}

# ── MCP server ────────────────────────────────────────────────────────────────

server: Server = Server("skill-" + SKILL_NAME)


@server.list_prompts()
async def list_prompts() -> list[types.Prompt]:
    return [
        types.Prompt(
            name=SKILL_NAME,
            description=SKILL_DESCRIPTION,
            arguments=[],
        )
    ]


@server.get_prompt()
async def get_prompt(
    name: str,
    arguments: dict[str, str] | None = None,  # noqa: ARG001
) -> types.GetPromptResult:
    if name != SKILL_NAME:
        raise ValueError(
            f"Unknown prompt: {{name!r}}. This server only provides {{SKILL_NAME!r}}."
        )
    return types.GetPromptResult(
        description=SKILL_DESCRIPTION,
        messages=[
            types.PromptMessage(
                role="user",
                content=types.TextContent(type="text", text=SKILL_BODY),
            )
        ],
    )


# ── entry point ───────────────────────────────────────────────────────────────


async def _run() -> None:
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            server.create_initialization_options(),
        )


def main() -> None:
    asyncio.run(_run())


if __name__ == "__main__":
    main()
'''


class McpServerExporter(SkillExporter):
    """Export a skill as a self-contained Python MCP Prompts server."""

    format = ExportFormat.MCP_SERVER

    def export(self, skill: Skill, body: str, output_dir: Path) -> Path:
        output_dir.mkdir(parents=True, exist_ok=True)

        instructions = (
            f"You are a specialist assistant for {skill.identity.name}.\n"
            f"{skill.description.text.strip()}\n\n"
            f"---\n\n"
            f"{body}"
        )

        content = _SERVER_TEMPLATE.format(
            name=skill.identity.name,
            slug=skill.identity.slug,
            version=skill.version,
            name_repr=repr(skill.identity.name),
            description_repr=repr(skill.description.text.strip()),
            body_repr=repr(instructions),
        )

        out = output_dir / f"{skill.identity.slug}-mcp-server.py"
        out.write_text(content, encoding="utf-8")
        return out
