#!/usr/bin/env python3
"""MCP Prompts server for skill: user-story-test-cases (v0.1.0).

Generated by skills-forge  <https://github.com/ficiverson/skills-forge>

Run with uvx (no install):
    uvx --from mcp mcp-run user-story-test-cases-mcp-server.py

Run with Python:
    pip install mcp
    python user-story-test-cases-mcp-server.py

Add to Claude Desktop (~/Library/Application Support/Claude/claude_desktop_config.json):
    {
      "mcpServers": {
        "user-story-test-cases": {
          "command": "python",
          "args": ["/absolute/path/to/user-story-test-cases-mcp-server.py"]
        }
      }
    }
"""

from __future__ import annotations

import asyncio

from mcp import types
from mcp.server import Server
from mcp.server.stdio import stdio_server

# ── skill payload ─────────────────────────────────────────────────────────────

SKILL_NAME: str = 'user-story-test-cases'
SKILL_DESCRIPTION: str = 'Use this skill when deriving structured test cases from a user story. Triggers on: acceptance criteria, edge cases, happy path, negative tests, BDD.'
SKILL_BODY: str = 'You are a specialist assistant for user-story-test-cases.\nUse this skill when deriving structured test cases from a user story. Triggers on: acceptance criteria, edge cases, happy path, negative tests, BDD.\n\n---\n\nSTARTER_CHARACTER = 🧪\n\n## Principles\n\n- Convert behavior into verifiable outcomes, not implementation details.\n- Cover happy path, alternate paths, and failure paths.\n- Keep each test atomic with one intent and one expected result.\n\n## Instructions\n\nWhen given a user story, produce:\n\n1. A short assumptions list for missing details.\n2. A traceability table mapping story/acceptance criteria to tests.\n3. A prioritized test suite with:\n   - ID\n   - title\n   - preconditions\n   - steps\n   - expected result\n   - type (functional, validation, edge, negative, non-functional if relevant)\n4. Clear Given/When/Then cases for key acceptance criteria.\n\nUse explicit input data and expected outputs whenever possible.\n\n## Constraints\n\n- Do not invent business rules; mark unknowns as assumptions/questions.\n- Avoid duplicate test cases that validate the same behavior.\n- Prefer language that product, QA, and engineering can all review.\n\n## Hints\n\n- Start by extracting entities, actions, and constraints from the story text.\n- Include boundary values and invalid inputs for each important field.\n- Add at least one regression test when a bugfix context is mentioned.'

# ── MCP server ────────────────────────────────────────────────────────────────

server: Server = Server("skill-" + SKILL_NAME)


@server.list_prompts()
async def list_prompts() -> list[types.Prompt]:
    return [
        types.Prompt(
            name=SKILL_NAME,
            description=SKILL_DESCRIPTION,
            arguments=[],
        )
    ]


@server.get_prompt()
async def get_prompt(
    name: str,
    arguments: dict[str, str] | None = None,  # noqa: ARG001
) -> types.GetPromptResult:
    if name != SKILL_NAME:
        raise ValueError(
            f"Unknown prompt: {name!r}. This server only provides {SKILL_NAME!r}."
        )
    return types.GetPromptResult(
        description=SKILL_DESCRIPTION,
        messages=[
            types.PromptMessage(
                role="user",
                content=types.TextContent(type="text", text=SKILL_BODY),
            )
        ],
    )


# ── entry point ───────────────────────────────────────────────────────────────


async def _run() -> None:
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            server.create_initialization_options(),
        )


def main() -> None:
    asyncio.run(_run())


if __name__ == "__main__":
    main()
