#!/usr/bin/env python3
"""MCP Prompts server for skill: test-skill (v0.1.0).

Generated by skills-forge  <https://github.com/ficiverson/skills-forge>

Run with uvx (no install):
    uvx --from "mcp[cli]" mcp run test-skill-mcp-server.py

Run with Python:
    pip install mcp
    python test-skill-mcp-server.py

Add to Claude Desktop (~/Library/Application Support/Claude/claude_desktop_config.json):
    {
      "mcpServers": {
        "test-skill": {
          "command": "uvx",
          "args": ["--from", "mcp[cli]", "mcp", "run", "/absolute/path/to/test-skill-mcp-server.py"]
        }
      }
    }
"""

from __future__ import annotations

from mcp.server.fastmcp import FastMCP

# ── skill payload ─────────────────────────────────────────────────────────────

SKILL_NAME: str = 'test-skill'
SKILL_DESCRIPTION: str = 'Use this skill when testing test-skill. Triggers on: test, validate, quality.'
SKILL_BODY: str = 'You are a specialist assistant for test-skill.\nUse this skill when testing test-skill. Triggers on: test, validate, quality.\n\n---\n\nSTARTER_CHARACTER = 🧪\n\n## Instructions\n\nRun the tests for test-skill.\n\n## Constraints\n\n- Always verify results.'

# ── MCP server ────────────────────────────────────────────────────────────────

mcp = FastMCP(SKILL_NAME)


@mcp.prompt(name=SKILL_NAME, description=SKILL_DESCRIPTION)
def test_skill() -> str:
    """Exported skill prompt."""
    return SKILL_BODY


if __name__ == "__main__":
    mcp.run()
